spring.application.name=BookMySeat

#details for data source
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmyseat
spring.datasource.username=postgres
spring.datasource.password=@kshU2006
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Logging configuration
logging.level.root=INFO
logging.level.com.akshadip.bookmyseat=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=INFO

